name       : devilspie2
version    : 0.41
release    : 1
source     :
    - http://download.savannah.gnu.org/releases/devilspie2/devilspie2_0.41-src.tar.gz : 7fe2139cbefb2c42b29f985344b876b3fc35a793048b9fb87def4fbe2853ebfd
license    : GPL-3.0
component  : system.utils
summary    : Devilspie2 is a window matching utility, allowing the user to perform scripted actions on windows as they are created.
description: |
    Devilspie2 is a window matching utility, allowing the user to perform scripted actions on windows as they are created. 
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(lua-5.1)
setup      : |
    # Fix for incorrect lua pkgconfig name
    sed -i 's:lua5.1:lua-5.1:g' Makefile
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
