name       : devilspie2
version    : '0.44'
release    : 10
source     :
    - https://github.com/dsalt/devilspie2/archive/refs/tags/v0.44.tar.gz : 07e5bd3a9af2a65b3e74049d3a4ec32cc7d687c6484495968cfb323a3da90bfc
license    : GPL-3.0-or-later
component  : system.utils
summary    : Devilspie2 is a window matching utility, allowing the user to perform scripted actions on windows as they are created.
description: |
    Devilspie2 is a window matching utility, allowing the user to perform scripted actions on windows as they are created.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(lua-5.3)
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
