name       : devilspie2
version    : '0.42'
release    : 2
source     :
    - http://download.savannah.gnu.org/releases/devilspie2/devilspie2_0.42-src.tar.gz : 11f5bc310fba4df404c057461ffb3fadac8ef51d211008c665c48f587a5a3f85
license    : GPL-3.0
component  : system.utils
summary    : Devilspie2 is a window matching utility, allowing the user to perform scripted actions on windows as they are created.
description: |
    Devilspie2 is a window matching utility, allowing the user to perform scripted actions on windows as they are created.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(lua-5.1)
setup      : |
    # Fix for incorrect lua pkgconfig name
    sed -i 's:lua5.1:lua-5.1:g' Makefile
build      : |
    %make PREFIX=/usr
install    : |
    %make_install PREFIX=/usr
